# Generated by Django 3.2.13 on 2023-01-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cookie',
            new_name='session_key',
        ),
    ]
