# Generated by Django 3.2.13 on 2023-01-12 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_cookie_customuser_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(choices=[('Like', 'Like'), ('Bought', 'Bought'), ('Share', 'Share'), ('Favorite', 'Favorite'), ('End', 'End'), ('View', 'View'), ('Click', 'Click')], max_length=20)),
                ('value', models.IntegerField(default=1)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
