version: "3"

services:
  ecommerce:
    build:
      context: .
    environment:
      - HOST=ecommerce.shamim.review
    depends_on:
      - ecommercedb

  ecommercedb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ecommerce'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ecommerce'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'nadgroup'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ecommerce-db3:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - ecommerce
      - ecommercedb

volumes:
  ecommerce-db:

