# Generated by Django 2.2 on 2023-01-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('uniq_code', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('asin', models.CharField(blank=True, max_length=20, null=True)),
                ('domain', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('str_category', models.CharField(blank=True, max_length=60, null=True)),
                ('str_categories', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default='not_found.jpg', null=True, upload_to='photos')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating', models.CharField(blank=True, max_length=80, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('product_status', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('p_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prices_alternate', models.CharField(blank=True, max_length=200, null=True)),
                ('price_alternate_mean', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_alternate_med', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_30_days', models.BooleanField(blank=True, null=True)),
                ('price_status', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_start_date', models.DateTimeField(blank=True, null=True)),
                ('discount_end_date', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=30, null=True)),
                ('off_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('coupon_off_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('store_link', models.URLField(blank=True, null=True)),
                ('store_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('store_name', models.CharField(blank=True, max_length=30, null=True)),
                ('s_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('channel', models.CharField(blank=True, max_length=30, null=True)),
                ('agent_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('agent_username', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ActionsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('action', models.CharField(choices=[('Like', 'Like'), ('Bought', 'Bought'), ('Share', 'Share'), ('Favorite', 'Favorite'), ('End', 'End'), ('View', 'View'), ('Click', 'Click')], max_length=20)),
                ('value', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
